title:              "freshblown"
tagline:            "어제의 내가 만든 오늘, 그리고 내일의 나"
email:              "freshblown@gmail.com"
description:        "하고싶은거 하나둘씩 하다보니 지금 내가 된 이야기"
author:             "freshblown"
baseurl:            "/"
url:                "https://freshblown.com/"
locale:             "ko_KR"
thumbnail:          "/img/freshblown_thumbnail.png"

# Social Profiles
twitter_username:   twitter_username
instagram_username: freshblown
facebook_username:  facebook_username
linkedin_username:  linkedin_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
disqus:
  shortname: http-freshblown-com
